version: "3.9"

services:
  game-server:
    build: .
    container_name: game_server
    # 서버 포트: 라즈베리파이에서 8081로 서비스하려는 요구 반영
    ports:
      - "8081:8081"
    environment:
      # Spring Boot 포트 강제 (파일 수정 없이 환경변수로 덮어쓰기)
      SERVER_PORT: "8081"

      # ✅ MySQL은 라즈베리파이(호스트)에서 로컬로 실행 중
      # 컨테이너에서 호스트로 접근하려면 host.docker.internal 매핑 필요 (아래 extra_hosts 참고)
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/cnwvdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      SPRING_DATASOURCE_USERNAME: "cnwv"
      SPRING_DATASOURCE_PASSWORD: "cnwv"

      # ✅ Redis 는 컨테이너로 실행 (아래 redis 서비스)
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"

      # 기존 properties 값을 덮어쓰기(선택): JPA 로그 등 필요시 유지
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

      # JWT 값은 기존과 동일하게 사용
      JWT_SECRET: "VGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktdGhhdC1tZWV0cy0zMi1ieXRlLW1pbi1yZXF1aXJlbWVudA=="
      JWT_ACCESSTOKENEXPIRATION: "900000"
      JWT_REFRESHTOKENEXPIRATION: "604800000"
    depends_on:
      - redis
    extra_hosts:
      # 리눅스에서 host.docker.internal 사용 가능하도록 설정
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_cnwv
    ports:
      - "6379:6379"
    restart: unless-stopped
